require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/airbrake.rb
    - config/initializers/application_controller_renderer.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/cookies_serializer.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - config/initializers/mime_types.rb
    - config/initializers/wrap_parameters.rb
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - db/seeds/**/*
    - Gemfile.lock
    - Rakefile
    - script/rails

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/factories/*

RSpec/EmptyLineAfterExampleGroup:
  Exclude:
    - spec/factories/*

RSpec/MissingExampleGroupArgument:
  Exclude:
    - spec/factories/*

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/Lambda:
  EnforcedStyle: literal

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%r': ()
    '%w': '[]'
    '%W': '[]'

Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
