# General Options
options:
  cache-config: true

# File Options
files:
  include:
    - '**/*.s+(c|a)ss'
  ignore:
    - '**/*+(vendor)/**/*.s+(c|a)ss'

# Rule Configuration
rules:
  no-transition-all: 0
  no-vendor-prefixes: 0
  no-color-literals: 2
  no-color-keywords: 2
  no-duplicate-properties: 1
  quotes:
    - 2
    -
      style: single
  no-css-comments: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  nesting-depth:
    - 1
    - max-depth: 3
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
        - padding
        - width
        - height
        - position
        - top
        - right
        - bottom
        - left
      ignore-custom-properties: true
  variable-name-format:
    - 2
    -
      convention: camelcase
  space-between-parens:
    - 2
    -
      include: false
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-after-colon:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
